version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node
    steps:
      - checkout

      - run: sudo chown -R circleci /usr/local/bundle
      - run: sudo chown -R circleci /usr/local/lib/node_modules

      - restore_cache:
          keys:
            - node_modules-{{ checksum "package-lock.json" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Installing ruby dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          name: Cache ruby dependencies
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Installing Node dependencies
          command: npm install

      - save_cache:
          name: Cache node dependencies
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Node run build
          command: npm run octopus:build

      - run:
          name: Build Jekyll
          command: bundle exec jekyll build --verbose
          environment:
            JEKYLL_ENV: production

      - run: ssh-keyscan $HOST >> ~/.ssh/known_hosts
      - run: sudo apt install rsync

      - add_ssh_keys:
          fingerprints:
            - "0f:c7:cd:c3:90:2c:a9:bb:32:ac:b0:f9:3b:a9:86:3e"

      - run:
          name: Deploy over ssh using Rsync
          command: |
            rsync -avzu /home/circleci/project/_site/ $USER@$HOST:/home/grumpy/new.grumpysailor.com --delete

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
